version: '3.3'

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_pass
      - MYSQL_DATABASE=mysql_db